### ISSUE TITLE
No such file or directory on AWS EC2 instances

### ISSUE THREAD

**Issue by galovics** [oracle-actions/login-ocir#18]
I'm unable to use the action on AWS EC2 instances as runners due to the following error:

```
ENOENT: no such file or directory, open '/home/ec2-user/.docker/config.json'
```

They are simple AL2 EC2 instances, nothing special about them yet the action gives an error. 

Usage looks like this:

```
....
      env:
        OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
        OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
        OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
        OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_KEY_FILE }}
        OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}
...
      - name: Log into OCIR
        uses: oracle-actions/login-ocir@v1.2.1
        id: login-ocir
        with:
          auth_token: ${{ secrets.OCI_DOCKER_USER_AUTH_TOKEN }}
....
```

Any ideas?
